import type { Metadata } from "next";
import "./globals.css";
import Navbarmain from "@/components/Navbarmain";
import dynamic from "next/dynamic";

// Dynamically import WhatsAppIcon to avoid hydration error
const WhatsAppIcon = dynamic(() => import("@/components/WhatsappIcon"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Grudhra Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Navbarmain />
        {children}
        <WhatsAppIcon />
      </body>
    </html>
  );
}
